FROM nginx:latest

COPY ./default_index.html /usr/share/nginx/html/index.html
COPY ./tenanta_index.html /usr/share/nginx/html/tenanta/index.html
COPY ./tenantb_index.html /usr/share/nginx/html/tenantb/index.html
